include("${SOURCE_DIR}/cmake/NativeUIPuglVisibility.cmake")
file(SHA256 "${PUGL_SOURCE}/src/mac.m" _before)
set(_stage "${TEST_BINARY_DIR}/pugl-visibility-contract")
nativeui_prepare_pugl_visibility("${PUGL_SOURCE}" "${_stage}")
file(SHA256 "${PUGL_SOURCE}/src/mac.m" _after)
if(NOT _before STREQUAL _after)
  message(FATAL_ERROR "Pugl source override was mutated")
endif()
file(SHA256 "${_stage}/src/mac.m" _patched)
if(_before STREQUAL _patched)
  message(FATAL_ERROR "Pugl visibility was not corrected")
endif()
nativeui_prepare_pugl_visibility("${PUGL_SOURCE}" "${_stage}")
file(SHA256 "${_stage}/src/mac.m" _again)
if(NOT _again STREQUAL _patched)
  message(FATAL_ERROR "Pugl staging is not deterministic")
endif()
file(READ "${_stage}/src/mac.m" _source)
foreach(_expected "[impl->wrapperView setHidden:YES];" "// NativeUI: show only the embedded child" "[view->impl->wrapperView setHidden:YES];")
  string(FIND "${_source}" "${_expected}" _position)
  if(_position EQUAL -1)
    message(FATAL_ERROR "Missing visibility fix ${_expected}")
  endif()
endforeach()
