cmake_minimum_required(VERSION 3.24)

if(NOT DEFINED SOURCE_DIR)
  message(FATAL_ERROR "SOURCE_DIR is required")
endif()

file(READ "${SOURCE_DIR}/CMakeLists.txt" _root_cmake)
file(READ "${SOURCE_DIR}/tests/CMakeLists.txt" _tests_cmake)
file(READ "${SOURCE_DIR}/examples/features/CMakeLists.txt" _features_cmake)
file(READ "${SOURCE_DIR}/include/nativeui/nativeui.hpp" _umbrella)
file(READ "${SOURCE_DIR}/tests/t051/CMakeLists.txt" _t051_cmake)
set(_feature_example_helper "${SOURCE_DIR}/cmake/NativeUIFeatureExamples.cmake")
set(_example "${SOURCE_DIR}/examples/features/t067_virtual_list.cpp")
set(_t051_benchmark "${SOURCE_DIR}/tests/t051/t067_virtual_list_benchmarks.cpp")

function(require_text haystack needle description)
  string(FIND "${haystack}" "${needle}" _index)
  if(_index EQUAL -1)
    message(FATAL_ERROR "T067 root integration contract: missing ${description}: ${needle}")
  endif()
endfunction()

if(NOT EXISTS "${_feature_example_helper}")
  message(FATAL_ERROR
    "T067 root integration contract: missing feature example discovery helper: ${_feature_example_helper}")
endif()
include("${_feature_example_helper}")
nativeui_discover_feature_examples(_feature_examples "${SOURCE_DIR}")
if(NOT "t067_virtual_list" IN_LIST _feature_examples)
  message(FATAL_ERROR
    "T067 root integration contract: t067_virtual_list is not discovered as a feature example")
endif()

require_text("${_root_cmake}" "add_subdirectory(examples)" "example directory registration")
require_text("${_root_cmake}" "add_subdirectory(tests)" "test directory registration")
require_text("${_features_cmake}" "nativeui_discover_feature_examples(" "automatic feature example registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_virtual_list_contract" "model contract registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_virtual_list_window_contract" "materialization-window contract registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_retained_tests" "retained runtime test registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_public_api_tests" "public API test registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_semantic_api_tests" "semantic API test registration")
require_text("${_tests_cmake}" "nativeui_add_core_test(nativeui_t067_visual_tests" "visual test registration")
string(REGEX MATCH "foreach\\(_header IN ITEMS[^)]*\\)" _public_header_loop "${_tests_cmake}")
if(_public_header_loop STREQUAL "")
  message(FATAL_ERROR
    "T067 root integration contract: missing public-header compile loop")
endif()
require_text("${_public_header_loop}" " virtual_list " "isolated virtual_list public-header compile coverage")
require_text("${_umbrella}" "#include <nativeui/virtual_list.hpp>" "virtual-list umbrella export")
require_text("${_t051_cmake}" "nativeui_t067_benchmark_contract" "T051 virtual-list benchmark target")
require_text("${_t051_cmake}" "t051.t067_virtual_list" "T051 virtual-list benchmark CTest registration")

if(NOT EXISTS "${_example}")
  message(FATAL_ERROR "T067 root integration contract: missing dedicated feature example: ${_example}")
endif()
if(NOT EXISTS "${_t051_benchmark}")
  message(FATAL_ERROR "T067 root integration contract: missing T051 virtual-list benchmark: ${_t051_benchmark}")
endif()
file(READ "${_example}" _example_source)
string(FIND "${_example_source}" "nativeui/detail/" _detail_index)
if(NOT _detail_index EQUAL -1)
  message(FATAL_ERROR "T067 feature example must use only the normal public NativeUI API")
endif()
require_text("${_features_cmake}" "add_test(NAME nativeui_example_" "feature example CTest registration")
require_text("${_features_cmake}" "nativeui_add_application(nativeui_example_" "feature application creation")

message(STATUS "T067 root integration contract passed")
