include_guard(GLOBAL)

function(_nativeui_binary_data_validate_id id context)
  if(id STREQUAL "")
    message(FATAL_ERROR "nativeui_add_binary_data: ${context} resource ID must not be empty")
  endif()
  if(id MATCHES "^/" OR id MATCHES "/$")
    message(FATAL_ERROR "nativeui_add_binary_data: ${context} resource ID '${id}' must be relative with no leading/trailing '/'")
  endif()
  string(FIND "${id}" "\\" _nativeui_backslash)
  if(NOT _nativeui_backslash EQUAL -1)
    message(FATAL_ERROR "nativeui_add_binary_data: ${context} resource ID '${id}' must not contain backslashes")
  endif()
  string(FIND "${id}" "//" _nativeui_double_slash)
  if(NOT _nativeui_double_slash EQUAL -1)
    message(FATAL_ERROR "nativeui_add_binary_data: ${context} resource ID '${id}' must not contain empty path segments")
  endif()
  string(REPLACE "/" ";" _nativeui_segments "${id}")
  foreach(_nativeui_segment IN LISTS _nativeui_segments)
    if(_nativeui_segment STREQUAL "." OR _nativeui_segment STREQUAL "..")
      message(FATAL_ERROR "nativeui_add_binary_data: ${context} resource ID '${id}' must not contain '.' or '..' segments")
    endif()
  endforeach()
endfunction()

function(nativeui_add_binary_data target)
  if(target STREQUAL "")
    message(FATAL_ERROR "nativeui_add_binary_data requires a non-empty target name")
  endif()
  if(TARGET "${target}")
    message(FATAL_ERROR "nativeui_add_binary_data: target '${target}' already exists")
  endif()

  cmake_parse_arguments(PARSE_ARGV 1 NUI "" "NAMESPACE;BASE_DIR" "SOURCES;ALIASES")
  if(NUI_UNPARSED_ARGUMENTS)
    message(FATAL_ERROR "nativeui_add_binary_data: unknown arguments: ${NUI_UNPARSED_ARGUMENTS}")
  endif()
  if(NUI_KEYWORDS_MISSING_VALUES)
    message(FATAL_ERROR "nativeui_add_binary_data: missing values for: ${NUI_KEYWORDS_MISSING_VALUES}")
  endif()
  if(NOT DEFINED NUI_NAMESPACE OR NUI_NAMESPACE STREQUAL "")
    message(FATAL_ERROR "nativeui_add_binary_data: NAMESPACE is required")
  endif()
  if(NOT NUI_NAMESPACE MATCHES "^[A-Za-z_][A-Za-z0-9_]*(::[A-Za-z_][A-Za-z0-9_]*)*$")
    message(FATAL_ERROR "nativeui_add_binary_data: invalid NAMESPACE '${NUI_NAMESPACE}'")
  endif()
  if(NOT NUI_SOURCES)
    message(FATAL_ERROR "nativeui_add_binary_data: SOURCES requires at least one file")
  endif()
  if(NOT TARGET NativeUI::Core)
    message(FATAL_ERROR "nativeui_add_binary_data requires NativeUI::Core")
  endif()

  get_property(_nativeui_namespaces GLOBAL PROPERTY NATIVEUI_BINARY_DATA_NAMESPACES)
  if(_nativeui_namespaces)
    list(FIND _nativeui_namespaces "${NUI_NAMESPACE}" _nativeui_namespace_index)
    if(NOT _nativeui_namespace_index EQUAL -1)
      message(FATAL_ERROR "nativeui_add_binary_data: NAMESPACE '${NUI_NAMESPACE}' is already used by another binary-data target")
    endif()
  endif()

  if(DEFINED NUI_BASE_DIR AND NOT NUI_BASE_DIR STREQUAL "")
    set(_nativeui_base_input "${NUI_BASE_DIR}")
  else()
    set(_nativeui_base_input "${CMAKE_CURRENT_SOURCE_DIR}")
  endif()
  if(NOT IS_ABSOLUTE "${_nativeui_base_input}")
    cmake_path(ABSOLUTE_PATH _nativeui_base_input BASE_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}" NORMALIZE OUTPUT_VARIABLE _nativeui_base_abs)
  else()
    cmake_path(NORMAL_PATH _nativeui_base_input OUTPUT_VARIABLE _nativeui_base_abs)
  endif()
  if(NOT EXISTS "${_nativeui_base_abs}" OR NOT IS_DIRECTORY "${_nativeui_base_abs}")
    message(FATAL_ERROR "nativeui_add_binary_data: BASE_DIR is not an existing directory: ${_nativeui_base_input}")
  endif()
  file(REAL_PATH "${_nativeui_base_abs}" _nativeui_base_real)

  set(_nativeui_source_tokens "${NUI_SOURCES}")
  set(_nativeui_seen_real_paths)
  set(_nativeui_source_keys)
  foreach(_nativeui_token IN LISTS _nativeui_source_tokens)
    string(FIND "${_nativeui_token}" "=" _nativeui_equals)
    if(NOT _nativeui_equals EQUAL -1)
      message(FATAL_ERROR "nativeui_add_binary_data: source token '${_nativeui_token}' contains '=' which is unsupported in v1")
    endif()
    if(IS_ABSOLUTE "${_nativeui_token}")
      set(_nativeui_candidate "${_nativeui_token}")
    else()
      set(_nativeui_candidate "${_nativeui_base_real}/${_nativeui_token}")
    endif()
    if(NOT EXISTS "${_nativeui_candidate}" OR IS_DIRECTORY "${_nativeui_candidate}")
      message(FATAL_ERROR "nativeui_add_binary_data: source is not an existing regular file: ${_nativeui_token}")
    endif()
    file(REAL_PATH "${_nativeui_candidate}" _nativeui_real)
    cmake_path(IS_PREFIX _nativeui_base_real "${_nativeui_real}" NORMALIZE _nativeui_inside_base)
    if(NOT _nativeui_inside_base)
      message(FATAL_ERROR "nativeui_add_binary_data: source escapes BASE_DIR: ${_nativeui_token}")
    endif()
    list(FIND _nativeui_seen_real_paths "${_nativeui_real}" _nativeui_duplicate_source)
    if(NOT _nativeui_duplicate_source EQUAL -1)
      message(FATAL_ERROR "nativeui_add_binary_data: duplicate canonical source: ${_nativeui_token}")
    endif()
    list(APPEND _nativeui_seen_real_paths "${_nativeui_real}")

    string(SHA256 _nativeui_token_hash "${_nativeui_token}")
    set("_nativeui_real_${_nativeui_token_hash}" "${_nativeui_real}")
    file(RELATIVE_PATH _nativeui_default_id "${_nativeui_base_real}" "${_nativeui_real}")
    file(TO_CMAKE_PATH "${_nativeui_default_id}" _nativeui_default_id)
    _nativeui_binary_data_validate_id("${_nativeui_default_id}" "default")
    set("_nativeui_id_${_nativeui_token_hash}" "${_nativeui_default_id}")
    list(APPEND _nativeui_source_keys "${_nativeui_token_hash}")
  endforeach()

  foreach(_nativeui_alias IN LISTS NUI_ALIASES)
    string(FIND "${_nativeui_alias}" "=" _nativeui_alias_equals)
    if(_nativeui_alias_equals LESS 1)
      message(FATAL_ERROR "nativeui_add_binary_data: invalid ALIASES entry '${_nativeui_alias}', expected <source-token>=<resource-id>")
    endif()
    string(SUBSTRING "${_nativeui_alias}" 0 ${_nativeui_alias_equals} _nativeui_alias_source)
    math(EXPR _nativeui_alias_id_offset "${_nativeui_alias_equals} + 1")
    string(SUBSTRING "${_nativeui_alias}" ${_nativeui_alias_id_offset} -1 _nativeui_alias_id)
    list(FIND _nativeui_source_tokens "${_nativeui_alias_source}" _nativeui_alias_source_index)
    if(_nativeui_alias_source_index EQUAL -1)
      message(FATAL_ERROR "nativeui_add_binary_data: ALIASES source token '${_nativeui_alias_source}' does not exactly match one SOURCES entry")
    endif()
    string(SHA256 _nativeui_alias_source_hash "${_nativeui_alias_source}")
    if(DEFINED "_nativeui_aliased_${_nativeui_alias_source_hash}")
      message(FATAL_ERROR "nativeui_add_binary_data: source '${_nativeui_alias_source}' has more than one alias")
    endif()
    _nativeui_binary_data_validate_id("${_nativeui_alias_id}" "alias")
    set("_nativeui_id_${_nativeui_alias_source_hash}" "${_nativeui_alias_id}")
    set("_nativeui_aliased_${_nativeui_alias_source_hash}" TRUE)
  endforeach()

  # Resource IDs are arbitrary validated UTF-8 strings and can legally contain
  # ';'. Never store those exact values in a CMake list: list semantics would
  # split a single ID into multiple entries. Sort and de-duplicate by the
  # fixed-width hexadecimal encoding of the original UTF-8 bytes instead, then
  # recover the untouched ID from a hex-keyed variable when generating code.
  set(_nativeui_id_sort_keys)
  foreach(_nativeui_key IN LISTS _nativeui_source_keys)
    set(_nativeui_id "${_nativeui_id_${_nativeui_key}}")
    string(HEX "${_nativeui_id}" _nativeui_id_sort_key)
    list(FIND _nativeui_id_sort_keys "${_nativeui_id_sort_key}" _nativeui_duplicate_id)
    if(NOT _nativeui_duplicate_id EQUAL -1)
      message(FATAL_ERROR "nativeui_add_binary_data: duplicate final resource ID '${_nativeui_id}'")
    endif()
    list(APPEND _nativeui_id_sort_keys "${_nativeui_id_sort_key}")
    string(SHA256 _nativeui_id_key "${_nativeui_id}")
    set("_nativeui_id_for_sort_key_${_nativeui_id_sort_key}" "${_nativeui_id}")
    set("_nativeui_source_for_id_${_nativeui_id_key}" "${_nativeui_real_${_nativeui_key}}")
  endforeach()
  list(SORT _nativeui_id_sort_keys CASE SENSITIVE ORDER ASCENDING)

  string(SHA256 _nativeui_target_hash "${target}")
  string(SUBSTRING "${_nativeui_target_hash}" 0 12 _nativeui_target_digest)

  set(_nativeui_root "${CMAKE_CURRENT_BINARY_DIR}/nativeui_binary_data/${target}")
  set(_nativeui_generated_include "${_nativeui_root}/include")
  set(_nativeui_header_dir "${_nativeui_generated_include}/nativeui_binary_data/${target}")
  set(_nativeui_source_dir "${_nativeui_root}/src")
  file(MAKE_DIRECTORY "${_nativeui_header_dir}" "${_nativeui_source_dir}")
  set(_nativeui_header "${_nativeui_header_dir}/resources.hpp")
  set(_nativeui_metadata "${_nativeui_source_dir}/resources.cpp")

  set(_nativeui_header_content "#pragma once\n\n#include <nativeui/embedded_resource.hpp>\n#include <span>\n\nnamespace ${NUI_NAMESPACE} {\nstd::span<const ui::EmbeddedResourceEntry> table() noexcept;\n} // namespace ${NUI_NAMESPACE}\n")
  file(WRITE "${_nativeui_header}" "${_nativeui_header_content}")

  set(_nativeui_payload_sources)
  set(_nativeui_forward_declarations "")
  set(_nativeui_id_arrays "")
  set(_nativeui_entries "")
  set(_nativeui_index 0)
  foreach(_nativeui_id_sort_key IN LISTS _nativeui_id_sort_keys)
    set(_nativeui_id "${_nativeui_id_for_sort_key_${_nativeui_id_sort_key}}")
    string(SHA256 _nativeui_id_hash "${_nativeui_id}")
    string(SUBSTRING "${_nativeui_id_hash}" 0 16 _nativeui_id_digest)
    set(_nativeui_symbol "nativeui_bd_${_nativeui_target_digest}_${_nativeui_id_digest}")
    set(_nativeui_source "${_nativeui_source_for_id_${_nativeui_id_hash}}")
    if(_nativeui_index LESS 10)
      set(_nativeui_index_text "000${_nativeui_index}")
    elseif(_nativeui_index LESS 100)
      set(_nativeui_index_text "00${_nativeui_index}")
    elseif(_nativeui_index LESS 1000)
      set(_nativeui_index_text "0${_nativeui_index}")
    else()
      set(_nativeui_index_text "${_nativeui_index}")
    endif()
    set(_nativeui_payload "${_nativeui_source_dir}/resource-${_nativeui_index_text}.cpp")
    add_custom_command(
      OUTPUT "${_nativeui_payload}"
      COMMAND "${CMAKE_COMMAND}"
        "-DINPUT=${_nativeui_source}"
        "-DOUTPUT=${_nativeui_payload}"
        "-DSYMBOL=${_nativeui_symbol}"
        -P "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/NativeUIEmbedResource.cmake"
      DEPENDS "${_nativeui_source}" "${CMAKE_CURRENT_FUNCTION_LIST_DIR}/NativeUIEmbedResource.cmake"
      VERBATIM
      COMMENT "Embedding NativeUI resource ${_nativeui_id}"
    )
    list(APPEND _nativeui_payload_sources "${_nativeui_payload}")
    string(APPEND _nativeui_forward_declarations "std::span<const std::byte> ${_nativeui_symbol}() noexcept;\n")

    string(HEX "${_nativeui_id}" _nativeui_id_hex)
    string(LENGTH "${_nativeui_id_hex}" _nativeui_id_hex_length)
    math(EXPR _nativeui_id_size "${_nativeui_id_hex_length} / 2")
    set(_nativeui_chars "")
    if(_nativeui_id_size GREATER 0)
      math(EXPR _nativeui_id_last "${_nativeui_id_size} - 1")
      foreach(_nativeui_char_index RANGE 0 ${_nativeui_id_last})
        math(EXPR _nativeui_char_offset "${_nativeui_char_index} * 2")
        string(SUBSTRING "${_nativeui_id_hex}" ${_nativeui_char_offset} 2 _nativeui_char_hex)
        string(APPEND _nativeui_chars "static_cast<char>(0x${_nativeui_char_hex}), ")
      endforeach()
    endif()
    set(_nativeui_id_array "nativeui_id_${_nativeui_index}")
    string(APPEND _nativeui_id_arrays "constexpr std::array<char, ${_nativeui_id_size}> ${_nativeui_id_array}{{${_nativeui_chars}}};\n")
    string(APPEND _nativeui_entries "    ui::EmbeddedResourceEntry{std::string_view{${_nativeui_id_array}.data(), ${_nativeui_id_array}.size()}, nativeui_binary_data_detail::${_nativeui_symbol}()},\n")
    math(EXPR _nativeui_index "${_nativeui_index} + 1")
  endforeach()
  list(LENGTH _nativeui_id_sort_keys _nativeui_count)

  set(_nativeui_metadata_content "#include <array>\n#include <cstddef>\n#include <span>\n#include <string_view>\n\n#include <nativeui/embedded_resource.hpp>\n#include <nativeui_binary_data/${target}/resources.hpp>\n\nnamespace nativeui_binary_data_detail {\n${_nativeui_forward_declarations}} // namespace nativeui_binary_data_detail\n\nnamespace {\n${_nativeui_id_arrays}} // namespace\n\nnamespace ${NUI_NAMESPACE} {\nstd::span<const ui::EmbeddedResourceEntry> table() noexcept {\n  static const std::array<ui::EmbeddedResourceEntry, ${_nativeui_count}> entries{{\n${_nativeui_entries}  }};\n  return entries;\n}\n} // namespace ${NUI_NAMESPACE}\n")
  file(WRITE "${_nativeui_metadata}" "${_nativeui_metadata_content}")

  add_library("${target}" STATIC "${_nativeui_metadata}" ${_nativeui_payload_sources})
  target_compile_features("${target}" PUBLIC cxx_std_20)
  target_include_directories("${target}" PUBLIC "${_nativeui_generated_include}")
  target_link_libraries("${target}" PUBLIC NativeUI::Core)
  set_target_properties("${target}" PROPERTIES
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN YES
    POSITION_INDEPENDENT_CODE ON
    NATIVEUI_BINARY_DATA_NAMESPACE "${NUI_NAMESPACE}"
  )

  set_property(GLOBAL APPEND PROPERTY NATIVEUI_BINARY_DATA_NAMESPACES "${NUI_NAMESPACE}")
endfunction()
