if(NOT DEFINED INPUT OR INPUT STREQUAL "")
  message(FATAL_ERROR "NativeUIEmbedResource requires INPUT")
endif()
if(NOT DEFINED OUTPUT OR OUTPUT STREQUAL "")
  message(FATAL_ERROR "NativeUIEmbedResource requires OUTPUT")
endif()
if(NOT DEFINED SYMBOL OR NOT SYMBOL MATCHES "^nativeui_bd_[0-9a-f]+_[0-9a-f]+$")
  message(FATAL_ERROR "NativeUIEmbedResource requires a valid SYMBOL")
endif()
string(LENGTH "${SYMBOL}" _nativeui_symbol_length)
if(NOT _nativeui_symbol_length EQUAL 41)
  message(FATAL_ERROR "NativeUIEmbedResource requires a valid SYMBOL")
endif()
string(SUBSTRING "${SYMBOL}" 12 12 _nativeui_target_digest)
string(SUBSTRING "${SYMBOL}" 24 1 _nativeui_separator)
string(SUBSTRING "${SYMBOL}" 25 16 _nativeui_id_digest)
if(NOT _nativeui_target_digest MATCHES "^[0-9a-f]+$" OR
   NOT _nativeui_separator STREQUAL "_" OR
   NOT _nativeui_id_digest MATCHES "^[0-9a-f]+$")
  message(FATAL_ERROR "NativeUIEmbedResource requires a valid SYMBOL")
endif()
if(NOT EXISTS "${INPUT}" OR IS_DIRECTORY "${INPUT}")
  message(FATAL_ERROR "NativeUIEmbedResource INPUT is not a regular file: ${INPUT}")
endif()

file(READ "${INPUT}" _nativeui_hex HEX)
string(LENGTH "${_nativeui_hex}" _nativeui_hex_length)
math(EXPR _nativeui_byte_count "${_nativeui_hex_length} / 2")

set(_nativeui_values "")
if(_nativeui_byte_count GREATER 0)
  math(EXPR _nativeui_last "${_nativeui_byte_count} - 1")
  foreach(_nativeui_index RANGE 0 ${_nativeui_last})
    math(EXPR _nativeui_offset "${_nativeui_index} * 2")
    string(SUBSTRING "${_nativeui_hex}" ${_nativeui_offset} 2 _nativeui_byte)
    string(APPEND _nativeui_values "    static_cast<std::byte>(0x${_nativeui_byte}),\n")
  endforeach()
endif()

get_filename_component(_nativeui_output_dir "${OUTPUT}" DIRECTORY)
file(MAKE_DIRECTORY "${_nativeui_output_dir}")
set(_nativeui_source "#include <array>\n#include <cstddef>\n#include <span>\n\nnamespace nativeui_binary_data_detail {\nstd::span<const std::byte> ${SYMBOL}() noexcept {\n  static constexpr std::array<std::byte, ${_nativeui_byte_count}> bytes = {{\n${_nativeui_values}  }};\n  return std::span<const std::byte>{bytes.data(), bytes.size()};\n}\n} // namespace nativeui_binary_data_detail\n")
file(WRITE "${OUTPUT}" "${_nativeui_source}")
